#!/usr/bin/env bash
# Is the package hex.pm serves the same code as the git tag of that version?
#
# THIS EXISTS BECAUSE A TAG AND A PUBLISHED RELEASE CAN DISAGREE AND NOTHING
# ANNOUNCES IT. `rebar3 hex publish' packages the WORKING TREE, not a tag, so a
# release made from an unclean or ahead-of-tag checkout ships something the tag
# does not name. On 2026-08-10 v2.4.0 was tagged one commit behind master, and
# the only way to know whether that mattered was to look.
#
# ⚠ DO NOT COMPARE HEX CHECKSUMS TO ANSWER THIS. The checksum covers
# contents.tar.gz, and gzip stores an mtime, so two builds of an identical tree
# produce different checksums. A mismatch there means nothing at all. This
# compares FILE CONTENTS, which is the question actually being asked.
#
# Usage:
#   scripts/is_hex_serving_what_git_says.sh 2.4.0
#   scripts/is_hex_serving_what_git_says.sh 2.4.0 v2.4.0     # explicit tag name
#
# To satisfy yourself it can fail, point it at a tag you know is wrong:
#   scripts/is_hex_serving_what_git_says.sh 2.4.0 v2.3.0     # must report 14 differing
# A comparison that has never been seen to fail is not evidence of agreement.
set -euo pipefail

VERSION="${1:?usage: $0 <version> [tag]}"
TAG="${2:-v${VERSION}}"
PKG=faber_tweann
REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

cd "$REPO_ROOT"

git rev-parse -q --verify "${TAG}^{commit}" >/dev/null 2>&1 || {
  echo "no such tag: ${TAG}"
  exit 1
}

echo "==> ${PKG} ${VERSION}, against tag ${TAG} ($(git rev-parse --short "${TAG}^{commit}"))"

# What hex serves.
mkdir -p "${WORK}/hex"
curl -sfL "https://repo.hex.pm/tarballs/${PKG}-${VERSION}.tar" -o "${WORK}/pkg.tar" || {
  echo "  NOT PUBLISHED, or the registry refused the fetch"
  exit 1
}
tar -xf "${WORK}/pkg.tar" -C "${WORK}" contents.tar.gz
tar -xzf "${WORK}/contents.tar.gz" -C "${WORK}/hex"

# What the tag holds, restricted to the paths the package actually ships. The
# files list lives in src/*.app.src; anything outside it is not part of the
# comparison, because it is not part of the release.
mkdir -p "${WORK}/git"
git archive "${TAG}" | tar -x -C "${WORK}/git"

# ⚠ *.app.src IS REGENERATED BY THE PACKAGING STEP, NOT COPIED. rebar3_hex
# writes the application term back out from its parsed form, which strips every
# comment and reflows the layout, so the packaged file NEVER matches the tagged
# one byte for byte and saying so is a false alarm rather than a finding. The
# question for that file is whether it holds the same TERMS, so it is consulted
# on both sides and the results compared.
same_terms() {
  erl -noshell -eval '
    [A, B] = init:get_plain_arguments(),
    {ok, TA} = file:consult(A),
    {ok, TB} = file:consult(B),
    halt(case TA =:= TB of true -> 0; false -> 1 end)
  ' -- "$1" "$2" 2>/dev/null
}

same_file() {
  case "$1" in
    *.app.src) same_terms "$2" "$3" ;;
    *) cmp -s "$2" "$3" ;;
  esac
}

echo
DIFFERENT=0
MISSING=0
for f in $(find "${WORK}/hex" -type f | sort); do
  rel="${f#"${WORK}/hex/"}"
  if [ ! -f "${WORK}/git/${rel}" ]; then
    echo "  ONLY IN THE PACKAGE  ${rel}"
    MISSING=$((MISSING + 1))
  elif ! same_file "${rel}" "${f}" "${WORK}/git/${rel}"; then
    echo "  DIFFERS              ${rel}"
    DIFFERENT=$((DIFFERENT + 1))
  fi
done

TOTAL=$(find "${WORK}/hex" -type f | wc -l)
echo
echo "  ${TOTAL} files in the package, ${DIFFERENT} differing, ${MISSING} absent from the tag"

# A file present at the tag but not in the package is NOT a fault: the files
# list ships a subset on purpose. Only the other direction is a finding.
[ "${DIFFERENT}" -eq 0 ] && [ "${MISSING}" -eq 0 ] &&
  echo "  hex is serving the tagged code." ||
  echo "  hex is NOT serving the tagged code. The tag does not name what consumers get."
